version: '3'

services:
  node-api:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    container_name: node-api
    restart: unless-stopped
    environment:
      - DB_NAME=$DB_NAME
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_HOST=$DB_HOST_URL
      - DB_PORT=$DB_PORT
    ports:
      - "4000:4000"
    volumes:
      - ./back-end:/usr/src/app
      - ./back-end/node_modules:/usr/src/app/node_modules
  web-app:
    build:
      context: ./challenge-react
      dockerfile: Dockerfile
    container_name: web-app
    restart: unless-stopped
    environment:
      - API_URL=$API_URL
    ports:
      - "3000:3000"
    depends_on:
      - node-api
    volumes:
      - ./challenge-react:/usr/src/app
      - ./challenge-react/node_modules:/usr/src/app/node_modules